import type { StyleSpecification } from "maplibre-gl";

const parks = [
  2083578322, 289097682, 6257706512, 287983382, 208357832, 289120012, 1430013,
  347755112,
];

export const atlas: StyleSpecification = {
  version: 8,
  sources: {
    terrarium: {
      type: "raster-dem",
      encoding: "terrarium",
      maxzoom: 12,
      tileSize: 256,
      tiles: [
        "https://s3.amazonaws.com/elevation-tiles-prod/terrarium/{z}/{x}/{y}.png",
      ],
      // url: "https://api.maptiler.com/tiles/terrain-rgb-v2/tiles.json?key=uXfXuebPlkoPXiY3TPcv",
    },
    georgia: {
      type: "vector",
      scheme: "xyz",
      url: "https://d3j4mgzjrheeg2.cloudfront.net/georgia.json",
    },
    atl1928: {
      type: "vector",
      scheme: "xyz",
      url: "https://d3j4mgzjrheeg2.cloudfront.net/atl-1928.json",
    },
  },
  layers: [
    {
      id: "land",
      type: "background",
      layout: {},
      paint: {
        "background-color": "#f4e0ae",
      },
    },
    // land layers
    {
      id: "landcover",
      type: "fill",
      source: "georgia",
      "source-layer": "landcover",
      minzoom: 7,
      layout: {},
      filter: ["in", ["id"], ["literal", parks]],
      paint: {
        "fill-antialias": false,
        "fill-color": [
          "match",
          ["get", "class"],
          "wood",
          "hsl(93, 24%, 50%)",
          "grass",
          "#708b34",
          "garden",
          "deeppink",
          ["rock", "sand"],
          "hsl(55, 62%, 88%)",
          "wetland",
          "hsl(151, 32%, 76%)",
          "ice",
          "hsl(240, 4%, 95%)",
          "hsl(68, 34%, 85%)",
        ],
        "fill-opacity": ["interpolate", ["linear"], ["zoom"], 7, 0.6, 12, 0.8],
      },
    },

    {
      id: "hillshade",
      type: "hillshade",
      source: "terrarium",
      layout: {},
      paint: {
        "hillshade-accent-color": "hsla(0, 0%, 0%, 0)",
        "hillshade-exaggeration": 0.6,
        "hillshade-highlight-color": "hsla(0, 0%, 0%, 0)",
        "hillshade-illumination-direction": 300,
        "hillshade-shadow-color": "hsl(115, 0%, 25%)",
      },
    },
    {
      id: "waterway-shadow",
      type: "line",
      source: "georgia",
      "source-layer": "waterway",
      minzoom: 6,
      layout: {
        "line-cap": ["step", ["zoom"], "butt", 11, "round"],
        "line-join": ["step", ["zoom"], "miter", 11, "round"],
      },
      paint: {
        "line-color": "hsl(229, 37%, 69%)",
        "line-opacity": ["interpolate", ["linear"], ["zoom"], 6, 0.6, 9, 1],
        "line-translate": [
          "interpolate",
          ["exponential", 1.2],
          ["zoom"],
          7,
          ["literal", [0, 0]],
          16,
          ["literal", [-1, -1]],
        ],
        "line-translate-anchor": "viewport",
        "line-width": [
          "interpolate",
          ["exponential", 1.3],
          ["zoom"],
          8,
          0.5,
          9,
          1,
          20,
          3,
        ],
      },
    },
    {
      id: "waterway",
      type: "line",
      source: "georgia",
      "source-layer": "waterway",
      minzoom: 3,
      layout: {
        "line-cap": ["step", ["zoom"], "butt", 11, "round"],
        "line-join": ["step", ["zoom"], "miter", 11, "round"],
      },
      paint: {
        "line-color": "hsl(209, 33%, 70%)",
        "line-width": [
          "interpolate",
          ["exponential", 1.3],
          ["zoom"],
          8,
          0.5,
          9,
          1,
          20,
          3,
        ],
      },
    },
    {
      id: "waterway_outer_glow",
      type: "line",
      source: "georgia",
      "source-layer": "waterway",
      minzoom: 4,
      layout: {
        "line-cap": ["step", ["zoom"], "butt", 11, "round"],
        "line-join": ["step", ["zoom"], "miter", 11, "round"],
      },
      paint: {
        "line-blur": ["interpolate", ["linear"], ["zoom"], 6, 5, 12, 10],
        "line-color": "hsl(209, 33%, 70%)",
        "line-opacity": ["interpolate", ["linear"], ["zoom"], 6, 0.2, 7, 0.4],
        "line-width": ["interpolate", ["linear"], ["zoom"], 6, 5, 12, 10],
      },
    },
    {
      id: "roads",
      type: "line",
      source: "atl1928",
      "source-layer": "roads1928",
      minzoom: 6,
      paint: {
        "line-color": "#413318",
        "line-width": [
          "interpolate",
          ["exponential", 5],
          ["zoom"],
          7,
          0,
          8,
          0.7,
          9,
          1.5,
          20,
          22,
        ],
      },
    },
    {
      id: "road-rail",
      type: "line",
      source: "atl1928",
      "source-layer": "railroads1928",
      minzoom: 10,
      paint: {
        "line-color": [
          "interpolate",
          ["linear"],
          ["zoom"],
          10,
          "#525830",
          16,
          "#31300d",
        ],
        "line-width": [
          "interpolate",
          ["exponential", 1.5],
          ["zoom"],
          10,
          0.5,
          20,
          1,
        ],
      },
    },
    {
      id: "road-rail-tracks",
      type: "line",
      source: "atl1928",
      "source-layer": "railroads1928",
      minzoom: 10,
      paint: {
        "line-color": [
          "interpolate",
          ["linear"],
          ["zoom"],
          10,
          "#525830",
          16,
          "#31300d",
        ],
        "line-dasharray": [0.2, 1],
        "line-opacity": ["interpolate", ["linear"], ["zoom"], 13.75, 0, 14, 1],
        "line-width": [
          "interpolate",
          ["exponential", 1.5],
          ["zoom"],
          10,
          4,
          20,
          8,
        ],
      },
    },
    {
      id: "streetcar",
      type: "line",
      source: "atl1928",
      "source-layer": "streetcars1924",
      minzoom: 16,
      paint: {
        "line-color": [
          "interpolate",
          ["linear"],
          ["zoom"],
          10,
          "#525830",
          16,
          "#31300d",
        ],
        "line-width": [
          "interpolate",
          ["exponential", 1.5],
          ["zoom"],
          5,
          0.5,
          10,
          1,
        ],
      },
    },
    {
      id: "streetcar-tracks",
      type: "line",
      source: "atl1928",
      "source-layer": "streetcars1924",
      minzoom: 13,
      paint: {
        "line-color": [
          "interpolate",
          ["linear"],
          ["zoom"],
          10,
          "#525830",
          16,
          "#31300d",
        ],
        "line-dasharray": [0.2, 1],
        "line-opacity": ["interpolate", ["linear"], ["zoom"], 13.75, 0, 14, 1],
        "line-width": [
          "interpolate",
          ["exponential", 1.5],
          ["zoom"],
          10,
          2,
          20,
          4,
        ],
      },
    },

    {
      id: "building",
      type: "fill",
      source: "atl1928",
      "source-layer": "buildings1928",
      minzoom: 12,
      maxzoom: 18,
      paint: {
        "fill-opacity": ["interpolate", ["linear"], ["zoom"], 12, 0, 16, 1],
        // "fill-color": "#474329",
        "fill-color": [
          "interpolate",
          ["exponential", 2],
          ["zoom"],
          12,
          "#474329",
          20,
          [
            "case",
            ["boolean", ["feature-state", "clicked"], false],
            "deeppink",
            ["==", ["get", "Identifier"], "BD36344"],
            "#4f452e",
            ["==", ["get", "Identifier"], "BD26475"],
            "#4f452e",
            ["==", ["get", "Land_Use"], "M"],
            "#AB59C9",
            ["==", ["get", "Land_Use"], "C"],
            "#E83333",
            ["==", ["get", "Land_Use"], "P"],
            "#2E6DFF",
            ["==", ["get", "Land_Use"], "R"],
            "#FFFF00",
            ["==", ["get", "Land_Use"], "TU"],
            "#FFCCFF",
            ["==", ["get", "Land_Use"], "TR"],
            "#FF6F00",
            ["==", ["get", "Land_Use"], "W"],
            "#5D4037",
            "#EBEBEB",
          ],
        ],
        "fill-outline-color": "#2e2616",
      },
    },
    {
      id: "building-3d",
      type: "fill-extrusion",
      source: "atl1928",
      "source-layer": "buildings1928",
      minzoom: 16,
      paint: {
        "fill-extrusion-color": [
          "interpolate",
          ["exponential", 2],
          ["zoom"],
          12,
          "#474329",
          20,
          [
            "case",
            ["boolean", ["feature-state", "clicked"], false],
            "deeppink",
            ["==", ["get", "Identifier"], "BD36344"],
            "#4f452e",
            ["==", ["get", "Identifier"], "BD26475"],
            "#4f452e",
            ["==", ["get", "Land_Use"], "M"],
            "#AB59C9",
            ["==", ["get", "Land_Use"], "C"],
            "#E83333",
            ["==", ["get", "Land_Use"], "P"],
            "#2E6DFF",
            ["==", ["get", "Land_Use"], "R"],
            "#FFFF00",
            ["==", ["get", "Land_Use"], "TU"],
            "#FFCCFF",
            ["==", ["get", "Land_Use"], "TR"],
            "#FF6F00",
            ["==", ["get", "Land_Use"], "W"],
            "#5D4037",
            "#EBEBEB",
          ],
        ],
        // "fill-extrusion-color": "hsl(35, 8%, 85%)",
        "fill-extrusion-height": [
          "case",
          ["has", "calc_ht"],
          ["*", ["get", "calc_ht"], 0.3048],
          3.5,
        ],
        "fill-extrusion-base": 3,
        "fill-extrusion-opacity": 1,
      },
    },
    {
      id: "road-label",
      type: "symbol",
      source: "atl1928",
      "source-layer": "roads1928",
      minzoom: 16,
      filter: ["!", ["in", "Unlabeled", ["get", "name"]]],
      layout: {
        "symbol-placement": "line",
        "text-field": ["get", "name"],
        "text-font": ["PT Sans Narrow Regular,Inter Regular"],
        "text-letter-spacing": 0.05,
        "text-max-angle": 30,
        "text-padding": 10,
        "text-pitch-alignment": "viewport",
        "text-size": ["interpolate", ["linear"], ["zoom"], 16, 9, 18, 10],
      },
      paint: {
        "text-color": "#282a0c",
        "text-halo-color": "#f7e5b3",
        "text-halo-width": [
          "interpolate",
          ["linear"],
          ["zoom"],
          10,
          1,
          18,
          2.5,
        ],
      },
    },
    {
      id: "railroad-label",
      type: "symbol",
      source: "atl1928",
      "source-layer": "railroads1928",
      minzoom: 10,
      filter: ["!", ["in", "Unidentified", ["get", "name"]]],
      layout: {
        "symbol-placement": "line",
        "text-field": ["get", "name"],
        "text-font": ["PT Sans Narrow Regular,Inter Regular"],
        "text-letter-spacing": 0.05,
        "text-max-angle": 30,
        "text-padding": 10,
        "text-pitch-alignment": "viewport",
        "text-size": ["interpolate", ["linear"], ["zoom"], 10, 9, 18, 16],
      },
      paint: {
        "text-color": "#282a0c",
        "text-halo-color": "#f7e5b3",
        "text-halo-width": [
          "interpolate",
          ["linear"],
          ["zoom"],
          10,
          1,
          18,
          2.5,
        ],
      },
    },
    {
      id: "streetcar-label",
      type: "symbol",
      source: "atl1928",
      "source-layer": "streetcars1924",
      minzoom: 16,
      layout: {
        "symbol-placement": "line",
        "symbol-spacing": 1000,
        "text-field": [
          "concat",
          "Route ",
          ["get", "Route_num"],
          " ",
          ["get", "R_Name"],
        ],
        "text-font": ["PT Sans Narrow Regular,Inter Regular"],
        "text-letter-spacing": 0.05,
        "text-max-angle": 30,
        "text-padding": 10,
        "text-pitch-alignment": "viewport",
        "text-size": ["interpolate", ["linear"], ["zoom"], 10, 9, 18, 12],
      },
      paint: {
        "text-color": "#282a0c",
        "text-halo-color": "#f7e5b3",
        "text-halo-width": [
          "interpolate",
          ["linear"],
          ["zoom"],
          16,
          1,
          20,
          1.5,
        ],
      },
    },
    {
      id: "commercial-labels",
      type: "symbol",
      source: "atl1928",
      "source-layer": "buildings1928",
      filter: ["==", ["get", "Land_Use"], "C"],
      minzoom: 15,
      layout: {
        "text-anchor": ["step", ["zoom"], "top-left", 8, "center"],
        "text-field": ["upcase", ["get", "Title"]],
        "text-font": ["PT Sans Narrow Regular,Inter Regular"],
        "text-justify": "auto",
        "text-line-height": 1.1,
        "text-max-width": 6,
        "text-letter-spacing": 0.25,
        "text-radial-offset": ["step", ["zoom"], 0.4, 8, 0],
        "text-size": [
          "interpolate",
          ["cubic-bezier", 0.2, 0, 0.9, 1],
          ["zoom"],
          12,
          6,
          16,
          12,
        ],
      },
      paint: {
        // "text-color": [
        //   "case",
        //   ["boolean", ["feature-state", "clicked"], false],
        //   "deeppink",
        //   ["==", ["get", "Identifier"], "BD36344"],
        //   "#4f452e",
        //   ["==", ["get", "Identifier"], "BD26475"],
        //   "#4f452e",
        //   ["==", ["get", "Land_Use"], "M"],
        //   "#AB59C9",
        //   ["==", ["get", "Land_Use"], "C"],
        //   "#E83333",
        //   ["==", ["get", "Land_Use"], "P"],
        //   "#2E6DFF",
        //   ["==", ["get", "Land_Use"], "R"],
        //   "#FFFF00",
        //   ["==", ["get", "Land_Use"], "TU"],
        //   "#FFCCFF",
        //   ["==", ["get", "Land_Use"], "TR"],
        //   "#FF6F00",
        //   ["==", ["get", "Land_Use"], "W"],
        //   "#5D4037",
        //   "#282a0c",
        // ],
        "text-color": "#f7e5b3",
        "text-halo-color": "#282a0c",
        "text-halo-width": [
          "interpolate",
          ["linear"],
          ["zoom"],
          10,
          1,
          18,
          2.5,
        ],
      },
    },
  ],
};
