import type { LayerSpecification } from "maplibre-gl";

// Road layers for OpenHistoricalMap tiles, visually matching the modern.ts road style.
//
// Property mapping from modern (OpenMapTiles) → OHM:
//   class         → type        (raw OSM highway tag value)
//   brunnel=bridge→ bridge=1    (integer)
//   brunnel=tunnel→ tunnel=1    (integer)
//   ramp=1        → type in [motorway_link, trunk_link, primary_link]
//   minor         → unclassified
//   street_limited→ residential
//
// sourceName should match the OHM vector tile source key in your style's sources object.
export const ohmRoadLayers = (sourceName = "ohm"): LayerSpecification[] => [
  // ── Tunnels ──────────────────────────────────────────────────────────────

  {
    id: "ohm-tunnel-case-ramp",
    type: "line",
    source: sourceName,
    "source-layer": "transport_lines",
    minzoom: 12,
    filter: [
      "all",
      ["==", ["coalesce", ["get", "tunnel"], 0], 1],
      [
        "step",
        ["zoom"],
        ["match", ["get", "type"], ["motorway", "trunk"], true, false],
        12,
        [
          "match",
          ["get", "type"],
          ["motorway", "trunk", "primary"],
          true,
          false,
        ],
        14,
        [
          "match",
          ["get", "type"],
          ["motorway", "trunk", "primary", "secondary", "tertiary"],
          true,
          false,
        ],
      ],
      [
        "match",
        ["get", "type"],
        ["motorway_link", "trunk_link", "primary_link"],
        true,
        false,
      ],
      ["==", ["geometry-type"], "LineString"],
    ],
    layout: {},
    paint: {
      "line-color": "hsl(0, 0%, 92%)",
      "line-gap-width": [
        "interpolate",
        ["exponential", 1.5],
        ["zoom"],
        12,
        ["match", ["get", "type"], ["motorway", "trunk", "primary"], 1, 0.5],
        13,
        ["match", ["get", "type"], ["motorway", "trunk", "primary"], 1.5, 0.5],
        15,
        ["match", ["get", "type"], ["motorway", "trunk", "primary"], 2, 1],
        18,
        ["match", ["get", "type"], ["motorway", "trunk", "primary"], 18, 10],
        22,
        ["match", ["get", "type"], ["motorway", "trunk", "primary"], 180, 100],
      ],
      "line-width": 2,
    },
  },

  {
    id: "ohm-tunnel-ramp",
    type: "line",
    source: sourceName,
    "source-layer": "transport_lines",
    minzoom: 12,
    filter: [
      "all",
      ["==", ["coalesce", ["get", "tunnel"], 0], 1],
      [
        "step",
        ["zoom"],
        ["match", ["get", "type"], ["motorway", "trunk"], true, false],
        12,
        [
          "match",
          ["get", "type"],
          ["motorway", "trunk", "primary"],
          true,
          false,
        ],
        14,
        [
          "match",
          ["get", "type"],
          ["motorway", "trunk", "primary", "secondary", "tertiary"],
          true,
          false,
        ],
      ],
      [
        "match",
        ["get", "type"],
        ["motorway_link", "trunk_link", "primary_link"],
        true,
        false,
      ],
      ["==", ["geometry-type"], "LineString"],
    ],
    paint: {
      "line-color": "hsl(0, 0%, 72%)",
      "line-width": [
        "interpolate",
        ["exponential", 1.5],
        ["zoom"],
        12,
        ["match", ["get", "type"], ["motorway", "trunk", "primary"], 1, 0.5],
        13,
        ["match", ["get", "type"], ["motorway", "trunk", "primary"], 1.5, 0.5],
        15,
        ["match", ["get", "type"], ["motorway", "trunk", "primary"], 2, 1],
        18,
        ["match", ["get", "type"], ["motorway", "trunk", "primary"], 18, 10],
        22,
        ["match", ["get", "type"], ["motorway", "trunk", "primary"], 180, 100],
      ],
    },
  },

  {
    id: "ohm-tunnel-case",
    type: "line",
    source: sourceName,
    "source-layer": "transport_lines",
    minzoom: 12,
    filter: [
      "all",
      ["==", ["coalesce", ["get", "tunnel"], 0], 1],
      [
        "step",
        ["zoom"],
        ["match", ["get", "type"], ["motorway", "trunk"], true, false],
        12,
        [
          "match",
          ["get", "type"],
          [
            "motorway",
            "trunk",
            "primary",
            "secondary",
            "tertiary",
            "unclassified",
            "residential",
            "track",
          ],
          true,
          false,
        ],
        14,
        [
          "match",
          ["get", "type"],
          [
            "motorway",
            "trunk",
            "primary",
            "secondary",
            "tertiary",
            "unclassified",
            "residential",
            "service",
            "track",
          ],
          true,
          false,
        ],
      ],
      [
        "match",
        ["get", "type"],
        ["motorway_link", "trunk_link", "primary_link"],
        false,
        true,
      ],
      ["==", ["geometry-type"], "LineString"],
    ],
    layout: {},
    paint: {
      "line-color": "hsl(0, 0%, 92%)",
      "line-gap-width": [
        "interpolate",
        ["exponential", 1.5],
        ["zoom"],
        12,
        [
          "match",
          ["get", "type"],
          ["motorway", "trunk"],
          4,
          ["primary", "secondary", "tertiary"],
          2.2,
          ["unclassified", "residential"],
          1,
          0.5,
        ],
        13,
        [
          "match",
          ["get", "type"],
          ["motorway", "trunk"],
          4,
          ["primary", "secondary", "tertiary"],
          2.5,
          ["unclassified", "residential"],
          1.5,
          0.5,
        ],
        15,
        [
          "match",
          ["get", "type"],
          ["motorway", "trunk"],
          6,
          ["primary", "secondary", "tertiary"],
          4,
          ["unclassified", "residential"],
          2,
          1,
        ],
        18,
        [
          "match",
          ["get", "type"],
          ["motorway", "trunk", "primary"],
          32,
          ["secondary", "tertiary"],
          26,
          ["unclassified", "residential"],
          18,
          10,
        ],
        22,
        [
          "match",
          ["get", "type"],
          ["motorway", "trunk", "primary"],
          320,
          ["secondary", "tertiary"],
          260,
          ["unclassified", "residential"],
          180,
          100,
        ],
      ],
      "line-width": 2,
    },
  },

  {
    id: "ohm-tunnel",
    type: "line",
    source: sourceName,
    "source-layer": "transport_lines",
    minzoom: 12,
    filter: [
      "all",
      ["==", ["coalesce", ["get", "tunnel"], 0], 1],
      [
        "step",
        ["zoom"],
        ["match", ["get", "type"], ["motorway", "trunk"], true, false],
        12,
        [
          "match",
          ["get", "type"],
          ["motorway", "trunk", "primary"],
          true,
          false,
        ],
        14,
        [
          "match",
          ["get", "type"],
          ["motorway", "trunk", "primary", "secondary", "tertiary"],
          true,
          false,
        ],
      ],
      [
        "match",
        ["get", "type"],
        ["motorway_link", "trunk_link", "primary_link"],
        false,
        true,
      ],
      ["==", ["geometry-type"], "LineString"],
    ],
    paint: {
      "line-color": "hsl(0, 0%, 72%)",
      "line-width": [
        "interpolate",
        ["exponential", 1.5],
        ["zoom"],
        12,
        [
          "match",
          ["get", "type"],
          ["motorway", "trunk"],
          4,
          ["primary", "secondary", "tertiary"],
          2.2,
          ["unclassified", "residential"],
          1,
          0.5,
        ],
        13,
        [
          "match",
          ["get", "type"],
          ["motorway", "trunk"],
          4,
          ["primary", "secondary", "tertiary"],
          2.5,
          ["unclassified", "residential"],
          1.5,
          0.5,
        ],
        15,
        [
          "match",
          ["get", "type"],
          ["motorway", "trunk"],
          6,
          ["primary", "secondary", "tertiary"],
          4,
          ["unclassified", "residential"],
          2,
          1,
        ],
        18,
        [
          "match",
          ["get", "type"],
          ["motorway", "trunk", "primary"],
          32,
          ["secondary", "tertiary"],
          26,
          ["unclassified", "residential"],
          18,
          10,
        ],
        22,
        [
          "match",
          ["get", "type"],
          ["motorway", "trunk", "primary"],
          320,
          ["secondary", "tertiary"],
          260,
          ["unclassified", "residential"],
          180,
          100,
        ],
      ],
    },
  },

  // ── Roads (no bridge/tunnel) ──────────────────────────────────────────────

  {
    id: "ohm-road-case-ramp",
    type: "line",
    source: sourceName,
    "source-layer": "transport_lines",
    minzoom: 6,
    filter: [
      "all",
      ["!=", ["coalesce", ["get", "bridge"], 0], 1],
      ["!=", ["coalesce", ["get", "tunnel"], 0], 1],
      [
        "match",
        ["get", "type"],
        ["motorway_link", "trunk_link", "primary_link"],
        true,
        false,
      ],
      ["==", ["geometry-type"], "LineString"],
    ],
    layout: {},
    paint: {
      "line-color": "hsl(0, 0%, 100%)",
      "line-gap-width": [
        "interpolate",
        ["exponential", 1.5],
        ["zoom"],
        12,
        ["match", ["get", "type"], ["motorway", "trunk", "primary"], 1, 0.5],
        13,
        ["match", ["get", "type"], ["motorway", "trunk", "primary"], 1.5, 0.5],
        15,
        ["match", ["get", "type"], ["motorway", "trunk", "primary"], 2, 1],
        18,
        ["match", ["get", "type"], ["motorway", "trunk", "primary"], 18, 10],
        22,
        ["match", ["get", "type"], ["motorway", "trunk", "primary"], 180, 100],
      ],
      "line-opacity": [
        "interpolate",
        ["exponential", 1.5],
        ["zoom"],
        6,
        0,
        7,
        1,
      ],
      "line-width": [
        "interpolate",
        ["exponential", 1.5],
        ["zoom"],
        5,
        0.6,
        8,
        0.7,
        12,
        2,
      ],
    },
  },

  {
    id: "ohm-road-case",
    type: "line",
    source: sourceName,
    "source-layer": "transport_lines",
    minzoom: 6,
    filter: [
      "all",
      ["!=", ["coalesce", ["get", "bridge"], 0], 1],
      ["!=", ["coalesce", ["get", "tunnel"], 0], 1],
      [
        "match",
        ["get", "type"],
        ["motorway_link", "trunk_link", "primary_link"],
        false,
        true,
      ],
      [
        "step",
        ["zoom"],
        ["match", ["get", "type"], ["motorway", "trunk"], true, false],
        12,
        [
          "match",
          ["get", "type"],
          ["motorway", "trunk", "primary", "secondary", "tertiary"],
          true,
          false,
        ],
        15,
        [
          "match",
          ["get", "type"],
          [
            "motorway",
            "trunk",
            "primary",
            "secondary",
            "tertiary",
            "unclassified",
            "residential",
          ],
          true,
          false,
        ],
      ],
      ["==", ["geometry-type"], "LineString"],
    ],
    layout: {},
    paint: {
      "line-color": "hsl(0, 0%, 100%)",
      "line-gap-width": [
        "interpolate",
        ["exponential", 1.5],
        ["zoom"],
        6,
        [
          "match",
          ["get", "type"],
          ["motorway", "trunk"],
          0.6,
          ["primary", "secondary", "tertiary"],
          0.1,
          0,
        ],
        7,
        [
          "match",
          ["get", "type"],
          ["motorway", "trunk"],
          1,
          ["primary", "secondary", "tertiary"],
          0.4,
          0,
        ],
        8,
        [
          "match",
          ["get", "type"],
          ["motorway", "trunk"],
          1.5,
          ["primary", "secondary", "tertiary"],
          0.4,
          0,
        ],
        12,
        [
          "match",
          ["get", "type"],
          ["motorway", "trunk"],
          4,
          ["primary", "secondary", "tertiary"],
          2.2,
          ["unclassified", "residential"],
          1,
          0.5,
        ],
        13,
        [
          "match",
          ["get", "type"],
          ["motorway", "trunk"],
          4,
          ["primary", "secondary", "tertiary"],
          3.5,
          [
            "motorway_link",
            "trunk_link",
            "primary_link",
            "unclassified",
            "residential",
          ],
          1.5,
          0.5,
        ],
        15,
        [
          "match",
          ["get", "type"],
          ["motorway", "trunk"],
          6,
          ["primary", "secondary", "tertiary"],
          5,
          [
            "motorway_link",
            "trunk_link",
            "primary_link",
            "unclassified",
            "residential",
          ],
          3,
          1.5,
        ],
        18,
        [
          "match",
          ["get", "type"],
          ["motorway", "trunk", "primary"],
          32,
          ["secondary", "tertiary"],
          26,
          ["unclassified", "residential"],
          18,
          10,
        ],
        22,
        [
          "match",
          ["get", "type"],
          ["motorway", "trunk", "primary"],
          320,
          ["secondary", "tertiary"],
          260,
          ["unclassified", "residential"],
          180,
          100,
        ],
      ],
      "line-opacity": [
        "interpolate",
        ["exponential", 1.5],
        ["zoom"],
        6,
        0,
        7,
        1,
      ],
      "line-width": [
        "interpolate",
        ["exponential", 1.5],
        ["zoom"],
        5,
        0.6,
        8,
        0.7,
        12,
        ["match", ["get", "type"], ["motorway", "trunk"], 2, 1.2],
      ],
    },
  },

  {
    id: "ohm-road-ramp",
    type: "line",
    source: sourceName,
    "source-layer": "transport_lines",
    minzoom: 10,
    filter: [
      "all",
      ["!=", ["coalesce", ["get", "bridge"], 0], 1],
      ["!=", ["coalesce", ["get", "tunnel"], 0], 1],
      [
        "match",
        ["get", "type"],
        ["motorway_link", "trunk_link", "primary_link"],
        true,
        false,
      ],
      ["==", ["geometry-type"], "LineString"],
    ],
    layout: {
      "line-cap": ["step", ["zoom"], "butt", 14, "round"],
      "line-join": ["step", ["zoom"], "miter", 14, "round"],
    },
    paint: {
      "line-color": [
        "interpolate",
        ["linear"],
        ["zoom"],
        10,
        [
          "match",
          ["get", "type"],
          ["motorway_link", "trunk_link"],
          "hsl(0, 0%, 46%)",
          "hsl(0, 0%, 59%)",
        ],
        22,
        "hsl(0, 0%, 62%)",
      ],
      "line-width": [
        "interpolate",
        ["exponential", 1.5],
        ["zoom"],
        12,
        ["match", ["get", "type"], ["motorway_link", "trunk_link"], 1, 0.5],
        13,
        ["match", ["get", "type"], ["motorway_link", "trunk_link"], 1.5, 0.5],
        15,
        ["match", ["get", "type"], ["motorway_link", "trunk_link"], 2, 1],
        18,
        ["match", ["get", "type"], ["motorway_link", "trunk_link"], 18, 10],
        22,
        ["match", ["get", "type"], ["motorway_link", "trunk_link"], 180, 100],
      ],
    },
  },

  {
    id: "ohm-road",
    type: "line",
    source: sourceName,
    "source-layer": "transport_lines",
    minzoom: 6,
    filter: [
      "all",
      ["!=", ["coalesce", ["get", "bridge"], 0], 1],
      ["!=", ["coalesce", ["get", "tunnel"], 0], 1],
      [
        "match",
        ["get", "type"],
        ["motorway_link", "trunk_link", "primary_link"],
        false,
        true,
      ],
      [
        "step",
        ["zoom"],
        ["match", ["get", "type"], ["motorway", "trunk"], true, false],
        7,
        [
          "match",
          ["get", "type"],
          ["motorway", "trunk", "primary"],
          true,
          false,
        ],
        8,
        [
          "match",
          ["get", "type"],
          ["motorway", "trunk", "primary", "secondary"],
          true,
          false,
        ],
        10,
        [
          "match",
          ["get", "type"],
          ["motorway", "trunk", "primary", "secondary", "tertiary"],
          true,
          false,
        ],
        11,
        [
          "match",
          ["get", "type"],
          [
            "motorway",
            "trunk",
            "primary",
            "secondary",
            "tertiary",
            "unclassified",
          ],
          true,
          false,
        ],
        12,
        [
          "match",
          ["get", "type"],
          [
            "motorway",
            "trunk",
            "primary",
            "secondary",
            "tertiary",
            "unclassified",
            "residential",
          ],
          true,
          false,
        ],
        13,
        [
          "match",
          ["get", "type"],
          [
            "motorway",
            "trunk",
            "primary",
            "secondary",
            "tertiary",
            "unclassified",
            "residential",
            "track",
          ],
          true,
          false,
        ],
        16,
        [
          "match",
          ["get", "type"],
          [
            "motorway",
            "trunk",
            "primary",
            "secondary",
            "tertiary",
            "unclassified",
            "residential",
            "service",
            "track",
          ],
          true,
          false,
        ],
      ],
      ["==", ["geometry-type"], "LineString"],
    ],
    layout: {
      "line-cap": ["step", ["zoom"], "butt", 14, "round"],
      "line-join": ["step", ["zoom"], "miter", 14, "round"],
    },
    paint: {
      "line-opacity": ["interpolate", ["linear"], ["zoom"], 10, 0.2, 20, 1],
      "line-color": [
        "interpolate",
        ["linear"],
        ["zoom"],
        6.9,
        [
          "match",
          ["get", "type"],
          ["motorway", "trunk", "primary"],
          "hsl(0, 0%, 100%)",
          "hsl(0, 1%, 100%)",
        ],
        7,
        [
          "match",
          ["get", "type"],
          ["motorway", "trunk"],
          "hsl(0, 0%, 59%)",
          "hsl(0, 0%, 100%)",
        ],
        9,
        [
          "match",
          ["get", "type"],
          ["motorway", "trunk", "primary", "secondary"],
          "hsl(0, 0%, 59%)",
          "hsl(0, 0%, 100%)",
        ],
        10,
        [
          "match",
          ["get", "type"],
          ["motorway", "trunk"],
          "hsl(0, 0%, 46%)",
          "hsl(0, 0%, 59%)",
        ],
        22,
        [
          "match",
          ["get", "type"],
          ["unclassified", "residential", "service", "track"],
          "hsl(0, 0%, 59%)",
          "hsl(0, 0%, 62%)",
        ],
      ],
      "line-width": [
        "interpolate",
        ["exponential", 1.5],
        ["zoom"],
        6,
        [
          "match",
          ["get", "type"],
          ["motorway", "trunk"],
          0.6,
          ["primary", "secondary", "tertiary"],
          0.1,
          0,
        ],
        7,
        [
          "match",
          ["get", "type"],
          ["motorway", "trunk"],
          1,
          ["primary", "secondary", "tertiary"],
          0.4,
          0,
        ],
        8,
        [
          "match",
          ["get", "type"],
          ["motorway", "trunk"],
          1.5,
          ["primary", "secondary", "tertiary"],
          0.4,
          0,
        ],
        12,
        [
          "match",
          ["get", "type"],
          ["motorway", "trunk"],
          4,
          ["primary", "secondary", "tertiary"],
          2.2,
          ["unclassified", "residential"],
          1,
          0.5,
        ],
        13,
        [
          "match",
          ["get", "type"],
          ["motorway", "trunk"],
          4,
          ["primary", "secondary", "tertiary"],
          3.5,
          ["unclassified", "residential"],
          2,
          1,
        ],
        15,
        [
          "match",
          ["get", "type"],
          ["motorway", "trunk"],
          6,
          ["primary", "secondary", "tertiary"],
          5,
          ["unclassified", "residential"],
          4,
          2,
        ],
        18,
        [
          "match",
          ["get", "type"],
          ["motorway", "trunk", "primary"],
          32,
          ["secondary", "tertiary"],
          26,
          ["unclassified", "residential"],
          18,
          10,
        ],
        22,
        [
          "match",
          ["get", "type"],
          ["motorway", "trunk", "primary"],
          320,
          ["secondary", "tertiary"],
          260,
          ["unclassified", "residential"],
          180,
          100,
        ],
      ],
    },
  },

  // ── Bridges ───────────────────────────────────────────────────────────────

  {
    id: "ohm-bridge-case-ramp",
    type: "line",
    source: sourceName,
    "source-layer": "transport_lines",
    minzoom: 13,
    filter: [
      "all",
      ["==", ["coalesce", ["get", "bridge"], 0], 1],
      [
        "match",
        ["get", "type"],
        ["motorway_link", "trunk_link", "primary_link"],
        true,
        false,
      ],
      ["==", ["geometry-type"], "LineString"],
    ],
    paint: {
      "line-color": "hsl(0, 0%, 100%)",
      "line-gap-width": [
        "interpolate",
        ["exponential", 1.5],
        ["zoom"],
        12,
        ["match", ["get", "type"], ["motorway_link", "trunk_link"], 1, 0.5],
        13,
        ["match", ["get", "type"], ["motorway_link", "trunk_link"], 1.5, 0.5],
        15,
        ["match", ["get", "type"], ["motorway_link", "trunk_link"], 2, 1],
        18,
        ["match", ["get", "type"], ["motorway_link", "trunk_link"], 18, 10],
        22,
        ["match", ["get", "type"], ["motorway_link", "trunk_link"], 180, 100],
      ],
      "line-width": [
        "interpolate",
        ["exponential", 1.5],
        ["zoom"],
        5,
        0.6,
        8,
        0.7,
        14,
        2,
      ],
    },
  },

  {
    id: "ohm-bridge-case",
    type: "line",
    source: sourceName,
    "source-layer": "transport_lines",
    minzoom: 12,
    filter: [
      "all",
      ["==", ["coalesce", ["get", "bridge"], 0], 1],
      [
        "match",
        ["get", "type"],
        ["motorway_link", "trunk_link", "primary_link"],
        false,
        true,
      ],
      [
        "step",
        ["zoom"],
        ["match", ["get", "type"], ["motorway", "trunk"], true, false],
        12,
        [
          "match",
          ["get", "type"],
          [
            "motorway",
            "trunk",
            "primary",
            "secondary",
            "tertiary",
            "unclassified",
            "residential",
            "track",
          ],
          true,
          false,
        ],
        14,
        [
          "match",
          ["get", "type"],
          [
            "motorway",
            "trunk",
            "primary",
            "secondary",
            "tertiary",
            "unclassified",
            "residential",
            "service",
            "track",
          ],
          true,
          false,
        ],
      ],
      ["==", ["geometry-type"], "LineString"],
    ],
    layout: {},
    paint: {
      "line-color": "hsl(0, 0%, 100%)",
      "line-gap-width": [
        "interpolate",
        ["exponential", 1.5],
        ["zoom"],
        6,
        [
          "match",
          ["get", "type"],
          ["motorway", "trunk"],
          0.6,
          ["primary", "secondary", "tertiary"],
          0.1,
          0,
        ],
        7,
        [
          "match",
          ["get", "type"],
          ["motorway", "trunk"],
          1,
          ["primary", "secondary", "tertiary"],
          0.4,
          0,
        ],
        8,
        [
          "match",
          ["get", "type"],
          ["motorway", "trunk"],
          1.5,
          ["primary", "secondary", "tertiary"],
          0.4,
          0,
        ],
        12,
        [
          "match",
          ["get", "type"],
          ["motorway", "trunk"],
          4,
          ["primary", "secondary", "tertiary"],
          2.2,
          ["unclassified", "residential"],
          1,
          0.5,
        ],
        13,
        [
          "match",
          ["get", "type"],
          ["motorway", "trunk"],
          4,
          ["primary", "secondary", "tertiary"],
          3.5,
          ["unclassified", "residential"],
          1.5,
          0.5,
        ],
        15,
        [
          "match",
          ["get", "type"],
          ["motorway", "trunk"],
          6,
          ["primary", "secondary", "tertiary"],
          5,
          ["unclassified", "residential"],
          3,
          1.5,
        ],
        18,
        [
          "match",
          ["get", "type"],
          ["motorway", "trunk", "primary"],
          32,
          ["secondary", "tertiary"],
          26,
          ["unclassified", "residential"],
          18,
          10,
        ],
        22,
        [
          "match",
          ["get", "type"],
          ["motorway", "trunk", "primary"],
          320,
          ["secondary", "tertiary"],
          260,
          ["unclassified", "residential"],
          180,
          100,
        ],
      ],
      "line-width": 2,
    },
  },

  {
    id: "ohm-bridge-ramp",
    type: "line",
    source: sourceName,
    "source-layer": "transport_lines",
    minzoom: 13,
    filter: [
      "all",
      ["==", ["coalesce", ["get", "bridge"], 0], 1],
      [
        "match",
        ["get", "type"],
        ["motorway_link", "trunk_link", "primary_link"],
        true,
        false,
      ],
      ["==", ["geometry-type"], "LineString"],
    ],
    layout: {
      "line-cap": ["step", ["zoom"], "butt", 14, "round"],
    },
    paint: {
      "line-color": [
        "interpolate",
        ["linear"],
        ["zoom"],
        10,
        [
          "match",
          ["get", "type"],
          ["motorway_link", "trunk_link"],
          "hsl(0, 0%, 46%)",
          "hsl(0, 0%, 59%)",
        ],
        22,
        "hsl(0, 0%, 62%)",
      ],
      "line-width": [
        "interpolate",
        ["exponential", 1.5],
        ["zoom"],
        12,
        ["match", ["get", "type"], ["motorway_link", "trunk_link"], 1, 0.5],
        13,
        ["match", ["get", "type"], ["motorway_link", "trunk_link"], 1.5, 0.5],
        15,
        ["match", ["get", "type"], ["motorway_link", "trunk_link"], 2, 1],
        18,
        ["match", ["get", "type"], ["motorway_link", "trunk_link"], 18, 10],
        22,
        ["match", ["get", "type"], ["motorway_link", "trunk_link"], 180, 100],
      ],
    },
  },

  {
    id: "ohm-bridge",
    type: "line",
    source: sourceName,
    "source-layer": "transport_lines",
    minzoom: 12,
    filter: [
      "all",
      ["==", ["coalesce", ["get", "bridge"], 0], 1],
      [
        "match",
        ["get", "type"],
        ["motorway_link", "trunk_link", "primary_link"],
        false,
        true,
      ],
      [
        "step",
        ["zoom"],
        ["match", ["get", "type"], ["motorway", "trunk"], true, false],
        12,
        [
          "match",
          ["get", "type"],
          [
            "motorway",
            "trunk",
            "primary",
            "secondary",
            "tertiary",
            "unclassified",
            "residential",
            "track",
          ],
          true,
          false,
        ],
        14,
        [
          "match",
          ["get", "type"],
          [
            "motorway",
            "trunk",
            "primary",
            "secondary",
            "tertiary",
            "unclassified",
            "residential",
            "service",
            "track",
          ],
          true,
          false,
        ],
      ],
      ["==", ["geometry-type"], "LineString"],
    ],
    layout: {
      "line-cap": ["step", ["zoom"], "butt", 14, "round"],
    },
    paint: {
      "line-color": [
        "interpolate",
        ["linear"],
        ["zoom"],
        6.9,
        [
          "match",
          ["get", "type"],
          ["motorway", "trunk", "primary"],
          "hsl(0, 0%, 100%)",
          "hsl(0, 1%, 100%)",
        ],
        7,
        [
          "match",
          ["get", "type"],
          ["motorway", "trunk"],
          "hsl(0, 0%, 46%)",
          "hsl(0, 0%, 100%)",
        ],
        9,
        [
          "match",
          ["get", "type"],
          ["motorway", "trunk", "primary", "secondary"],
          "hsl(0, 0%, 59%)",
          "hsl(0, 0%, 100%)",
        ],
        10,
        [
          "match",
          ["get", "type"],
          ["motorway", "trunk"],
          "hsl(0, 0%, 46%)",
          "hsl(0, 0%, 59%)",
        ],
        22,
        [
          "match",
          ["get", "type"],
          ["unclassified", "residential", "service", "track"],
          "hsl(0, 0%, 59%)",
          "hsl(0, 0%, 62%)",
        ],
      ],
      "line-width": [
        "interpolate",
        ["exponential", 1.5],
        ["zoom"],
        12,
        [
          "match",
          ["get", "type"],
          ["motorway", "trunk"],
          4,
          ["primary", "secondary", "tertiary"],
          2.2,
          ["unclassified", "residential"],
          1,
          0.5,
        ],
        13,
        [
          "match",
          ["get", "type"],
          ["motorway", "trunk"],
          4,
          ["primary", "secondary", "tertiary"],
          3.5,
          ["unclassified", "residential"],
          2,
          1,
        ],
        15,
        [
          "match",
          ["get", "type"],
          ["motorway", "trunk"],
          6,
          ["primary", "secondary", "tertiary"],
          5,
          ["unclassified", "residential"],
          4,
          2,
        ],
        18,
        [
          "match",
          ["get", "type"],
          ["motorway", "trunk", "primary"],
          32,
          ["secondary", "tertiary"],
          26,
          ["unclassified", "residential"],
          18,
          10,
        ],
        22,
        [
          "match",
          ["get", "type"],
          ["motorway", "trunk", "primary"],
          320,
          ["secondary", "tertiary"],
          260,
          ["unclassified", "residential"],
          180,
          100,
        ],
      ],
    },
  },
];
