import chroma from "chroma-js";
import type { LayerSpecification } from "maplibre-gl";
import { roadColor } from "./colors";

export const labelColor = "#2F323A";
export const buildingColor = "#2F323A";
const minZoom = 13;
const minWidth = 0.5;

export const transportation: LayerSpecification[] = [
  {
    type: "line",
    source: "georgia",
    "source-layer": "transportation",
    id: "rail_dashes_tunnel_all_in,get,subclass,literal,rail,preserved_match,get,service,siding,spur,yard,false,true",
    filter: [
      "all",
      ["match", ["get", "brunnel"], "tunnel", true, false],
      ["in", ["get", "class"], ["literal", ["rail", "transit"]]],
      [
        "all",
        ["in", ["get", "subclass"], ["literal", ["rail", "preserved"]]],
        ["match", ["get", "service"], ["siding", "spur", "yard"], false, true],
      ],
      ["!=", ["get", "service"], "crossover"],
    ],
    minzoom: 10,
    layout: {
      "line-cap": "butt",
      "line-join": "bevel",
      visibility: "visible",
    },
    paint: {
      "line-color": [
        "match",
        ["get", "brunnel"],
        "tunnel",
        "hsl(0, 0%, 90%)",
        [
          "match",
          ["get", "subclass"],
          "subway",
          "hsl(0, 0%, 50%)",
          "light_rail",
          "hsl(0, 0%, 50%)",
          "tram",
          "hsl(0, 0%, 60%)",
          "monorail",
          "hsl(0, 0%, 50%)",
          "funicular",
          "hsl(0, 0%, 50%)",
          "narrow_gauge",
          "hsl(0, 0%, 60%)",
          "hsl(0, 0%, 60%)",
        ],
      ],
      "line-opacity": [
        "step",
        ["zoom"],
        [
          "match",
          ["get", "subclass"],
          ["rail", "preserved", "narrow_gauge"],
          1,
          0,
        ],
        14,
        1,
      ],
      "line-width": [
        "interpolate",
        ["exponential", 1.2],
        ["zoom"],
        8,
        [
          "match",
          ["get", "subclass"],
          ["rail", "preserved", "narrow_gauge", "subway"],
          [
            "match",
            ["get", "service"],
            ["siding", "spur", "yard"],
            0.375,
            0.75,
          ],
          "monorail",
          [
            "match",
            ["get", "service"],
            ["siding", "spur", "yard"],
            0.30000000000000004,
            0.6000000000000001,
          ],
          [
            "match",
            ["get", "service"],
            ["siding", "spur", "yard"],
            0.234375,
            0.46875,
          ],
        ],
        12,
        [
          "match",
          ["get", "subclass"],
          ["rail", "preserved", "narrow_gauge", "subway"],
          ["match", ["get", "service"], ["siding", "spur", "yard"], 1.5, 3],
          "monorail",
          [
            "match",
            ["get", "service"],
            ["siding", "spur", "yard"],
            1.2000000000000002,
            2.4000000000000004,
          ],
          [
            "match",
            ["get", "service"],
            ["siding", "spur", "yard"],
            0.9375,
            1.875,
          ],
        ],
        20,
        [
          "match",
          ["get", "subclass"],
          ["rail", "preserved", "narrow_gauge", "subway"],
          ["match", ["get", "service"], ["siding", "spur", "yard"], 6, 12],
          "monorail",
          [
            "match",
            ["get", "service"],
            ["siding", "spur", "yard"],
            4.800000000000001,
            9.600000000000001,
          ],
          ["match", ["get", "service"], ["siding", "spur", "yard"], 3.75, 7.5],
        ],
      ],
      "line-dasharray": [0.16666666666666666, 4.166666666666667],
    },
  },
  {
    type: "line",
    source: "georgia",
    "source-layer": "transportation",
    id: "rail_dashes_tunnel_all_in,get,subclass,literal,rail,preserved_match,get,service,siding,spur,yard,true,false",
    filter: [
      "all",
      ["match", ["get", "brunnel"], "tunnel", true, false],
      ["in", ["get", "class"], ["literal", ["rail", "transit"]]],
      [
        "all",
        ["in", ["get", "subclass"], ["literal", ["rail", "preserved"]]],
        ["match", ["get", "service"], ["siding", "spur", "yard"], true, false],
      ],
      ["!=", ["get", "service"], "crossover"],
    ],
    minzoom: 10,
    layout: {
      "line-cap": "butt",
      "line-join": "bevel",
      visibility: "visible",
    },
    paint: {
      "line-color": [
        "match",
        ["get", "brunnel"],
        "tunnel",
        "hsl(0, 0%, 90%)",
        [
          "match",
          ["get", "subclass"],
          "subway",
          "hsl(0, 0%, 50%)",
          "light_rail",
          "hsl(0, 0%, 50%)",
          "tram",
          "hsl(0, 0%, 60%)",
          "monorail",
          "hsl(0, 0%, 50%)",
          "funicular",
          "hsl(0, 0%, 50%)",
          "narrow_gauge",
          "hsl(0, 0%, 60%)",
          "hsl(0, 0%, 60%)",
        ],
      ],
      "line-opacity": [
        "step",
        ["zoom"],
        [
          "match",
          ["get", "subclass"],
          ["rail", "preserved", "narrow_gauge"],
          1,
          0,
        ],
        14,
        1,
      ],
      "line-width": [
        "interpolate",
        ["exponential", 1.2],
        ["zoom"],
        8,
        [
          "match",
          ["get", "subclass"],
          ["rail", "preserved", "narrow_gauge", "subway"],
          ["match", ["get", "service"], ["siding", "spur", "yard"], 0.5, 1],
          "monorail",
          ["match", ["get", "service"], ["siding", "spur", "yard"], 0.4, 0.8],
          [
            "match",
            ["get", "service"],
            ["siding", "spur", "yard"],
            0.3125,
            0.625,
          ],
        ],
        12,
        [
          "match",
          ["get", "subclass"],
          ["rail", "preserved", "narrow_gauge", "subway"],
          ["match", ["get", "service"], ["siding", "spur", "yard"], 2, 4],
          "monorail",
          ["match", ["get", "service"], ["siding", "spur", "yard"], 1.6, 3.2],
          ["match", ["get", "service"], ["siding", "spur", "yard"], 1.25, 2.5],
        ],
        20,
        [
          "match",
          ["get", "subclass"],
          ["rail", "preserved", "narrow_gauge", "subway"],
          ["match", ["get", "service"], ["siding", "spur", "yard"], 8, 16],
          "monorail",
          ["match", ["get", "service"], ["siding", "spur", "yard"], 6.4, 12.8],
          ["match", ["get", "service"], ["siding", "spur", "yard"], 5, 10],
        ],
      ],
      "line-dasharray": [0.125, 6.25],
    },
  },
  {
    type: "line",
    source: "georgia",
    "source-layer": "transportation",
    id: "rail_dashes_tunnel_all_,get,subclass,narrow_gauge_match,get,service,siding,spur,yard,false,true",
    filter: [
      "all",
      ["match", ["get", "brunnel"], "tunnel", true, false],
      ["in", ["get", "class"], ["literal", ["rail", "transit"]]],
      [
        "all",
        ["==", ["get", "subclass"], "narrow_gauge"],
        ["match", ["get", "service"], ["siding", "spur", "yard"], false, true],
      ],
      ["!=", ["get", "service"], "crossover"],
    ],
    minzoom: 10,
    layout: {
      "line-cap": "butt",
      "line-join": "bevel",
      visibility: "visible",
    },
    paint: {
      "line-color": [
        "match",
        ["get", "brunnel"],
        "tunnel",
        "hsl(0, 0%, 90%)",
        [
          "match",
          ["get", "subclass"],
          "subway",
          "hsl(0, 0%, 50%)",
          "light_rail",
          "hsl(0, 0%, 50%)",
          "tram",
          "hsl(0, 0%, 60%)",
          "monorail",
          "hsl(0, 0%, 50%)",
          "funicular",
          "hsl(0, 0%, 50%)",
          "narrow_gauge",
          "hsl(0, 0%, 60%)",
          "hsl(0, 0%, 60%)",
        ],
      ],
      "line-opacity": [
        "step",
        ["zoom"],
        [
          "match",
          ["get", "subclass"],
          ["rail", "preserved", "narrow_gauge"],
          1,
          0,
        ],
        14,
        1,
      ],
      "line-width": [
        "interpolate",
        ["exponential", 1.2],
        ["zoom"],
        8,
        [
          "match",
          ["get", "subclass"],
          ["rail", "preserved", "narrow_gauge", "subway"],
          ["match", ["get", "service"], ["siding", "spur", "yard"], 0.25, 0.5],
          "monorail",
          ["match", ["get", "service"], ["siding", "spur", "yard"], 0.2, 0.4],
          [
            "match",
            ["get", "service"],
            ["siding", "spur", "yard"],
            0.15625,
            0.3125,
          ],
        ],
        12,
        [
          "match",
          ["get", "subclass"],
          ["rail", "preserved", "narrow_gauge", "subway"],
          ["match", ["get", "service"], ["siding", "spur", "yard"], 1, 2],
          "monorail",
          ["match", ["get", "service"], ["siding", "spur", "yard"], 0.8, 1.6],
          [
            "match",
            ["get", "service"],
            ["siding", "spur", "yard"],
            0.625,
            1.25,
          ],
        ],
        20,
        [
          "match",
          ["get", "subclass"],
          ["rail", "preserved", "narrow_gauge", "subway"],
          ["match", ["get", "service"], ["siding", "spur", "yard"], 4, 8],
          "monorail",
          ["match", ["get", "service"], ["siding", "spur", "yard"], 3.2, 6.4],
          ["match", ["get", "service"], ["siding", "spur", "yard"], 2.5, 5],
        ],
      ],
      "line-dasharray": [0.25, 0.25, 0.25, 3.75],
    },
  },
  {
    type: "line",
    source: "georgia",
    "source-layer": "transportation",
    id: "rail_dashes_tunnel_all_,get,subclass,narrow_gauge_match,get,service,siding,spur,yard,true,false",
    filter: [
      "all",
      ["match", ["get", "brunnel"], "tunnel", true, false],
      ["in", ["get", "class"], ["literal", ["rail", "transit"]]],
      [
        "all",
        ["==", ["get", "subclass"], "narrow_gauge"],
        ["match", ["get", "service"], ["siding", "spur", "yard"], true, false],
      ],
      ["!=", ["get", "service"], "crossover"],
    ],
    minzoom: 10,
    layout: {
      "line-cap": "butt",
      "line-join": "bevel",
      visibility: "visible",
    },
    paint: {
      "line-color": [
        "match",
        ["get", "brunnel"],
        "tunnel",
        "hsl(0, 0%, 90%)",
        [
          "match",
          ["get", "subclass"],
          "subway",
          "hsl(0, 0%, 50%)",
          "light_rail",
          "hsl(0, 0%, 50%)",
          "tram",
          "hsl(0, 0%, 60%)",
          "monorail",
          "hsl(0, 0%, 50%)",
          "funicular",
          "hsl(0, 0%, 50%)",
          "narrow_gauge",
          "hsl(0, 0%, 60%)",
          "hsl(0, 0%, 60%)",
        ],
      ],
      "line-opacity": [
        "step",
        ["zoom"],
        [
          "match",
          ["get", "subclass"],
          ["rail", "preserved", "narrow_gauge"],
          1,
          0,
        ],
        14,
        1,
      ],
      "line-width": [
        "interpolate",
        ["exponential", 1.2],
        ["zoom"],
        8,
        [
          "match",
          ["get", "subclass"],
          ["rail", "preserved", "narrow_gauge", "subway"],
          [
            "match",
            ["get", "service"],
            ["siding", "spur", "yard"],
            0.375,
            0.75,
          ],
          "monorail",
          [
            "match",
            ["get", "service"],
            ["siding", "spur", "yard"],
            0.30000000000000004,
            0.6000000000000001,
          ],
          [
            "match",
            ["get", "service"],
            ["siding", "spur", "yard"],
            0.234375,
            0.46875,
          ],
        ],
        12,
        [
          "match",
          ["get", "subclass"],
          ["rail", "preserved", "narrow_gauge", "subway"],
          ["match", ["get", "service"], ["siding", "spur", "yard"], 1.5, 3],
          "monorail",
          [
            "match",
            ["get", "service"],
            ["siding", "spur", "yard"],
            1.2000000000000002,
            2.4000000000000004,
          ],
          [
            "match",
            ["get", "service"],
            ["siding", "spur", "yard"],
            0.9375,
            1.875,
          ],
        ],
        20,
        [
          "match",
          ["get", "subclass"],
          ["rail", "preserved", "narrow_gauge", "subway"],
          ["match", ["get", "service"], ["siding", "spur", "yard"], 6, 12],
          "monorail",
          [
            "match",
            ["get", "service"],
            ["siding", "spur", "yard"],
            4.800000000000001,
            9.600000000000001,
          ],
          ["match", ["get", "service"], ["siding", "spur", "yard"], 3.75, 7.5],
        ],
      ],
      "line-dasharray": [
        0.16666666666666666, 0.3333333333333333, 0.16666666666666666, 5,
      ],
    },
  },
  {
    type: "line",
    source: "georgia",
    "source-layer": "transportation",
    id: "rail_dashes_tunnel__get,subclass_funicular",
    filter: [
      "all",
      ["match", ["get", "brunnel"], "tunnel", true, false],
      ["in", ["get", "class"], ["literal", ["rail", "transit"]]],
      ["==", ["get", "subclass"], "funicular"],
      ["!=", ["get", "service"], "crossover"],
    ],
    minzoom: 14,
    layout: {
      "line-cap": "butt",
      "line-join": "bevel",
      visibility: "visible",
    },
    paint: {
      "line-color": [
        "match",
        ["get", "brunnel"],
        "tunnel",
        "hsl(0, 0%, 90%)",
        [
          "match",
          ["get", "subclass"],
          "subway",
          "hsl(0, 0%, 50%)",
          "light_rail",
          "hsl(0, 0%, 50%)",
          "tram",
          "hsl(0, 0%, 60%)",
          "monorail",
          "hsl(0, 0%, 50%)",
          "funicular",
          "hsl(0, 0%, 50%)",
          "narrow_gauge",
          "hsl(0, 0%, 60%)",
          "hsl(0, 0%, 60%)",
        ],
      ],
      "line-opacity": [
        "step",
        ["zoom"],
        [
          "match",
          ["get", "subclass"],
          ["rail", "preserved", "narrow_gauge"],
          1,
          0,
        ],
        14,
        1,
      ],
      "line-width": [
        "interpolate",
        ["exponential", 1.2],
        ["zoom"],
        8,
        [
          "match",
          ["get", "subclass"],
          ["rail", "preserved", "narrow_gauge", "subway"],
          [
            "match",
            ["get", "service"],
            ["siding", "spur", "yard"],
            0.2875,
            0.575,
          ],
          "monorail",
          [
            "match",
            ["get", "service"],
            ["siding", "spur", "yard"],
            0.22999999999999998,
            0.45999999999999996,
          ],
          [
            "match",
            ["get", "service"],
            ["siding", "spur", "yard"],
            0.1796875,
            0.359375,
          ],
        ],
        12,
        [
          "match",
          ["get", "subclass"],
          ["rail", "preserved", "narrow_gauge", "subway"],
          ["match", ["get", "service"], ["siding", "spur", "yard"], 1.15, 2.3],
          "monorail",
          [
            "match",
            ["get", "service"],
            ["siding", "spur", "yard"],
            0.9199999999999999,
            1.8399999999999999,
          ],
          [
            "match",
            ["get", "service"],
            ["siding", "spur", "yard"],
            0.71875,
            1.4375,
          ],
        ],
        20,
        [
          "match",
          ["get", "subclass"],
          ["rail", "preserved", "narrow_gauge", "subway"],
          ["match", ["get", "service"], ["siding", "spur", "yard"], 4.6, 9.2],
          "monorail",
          [
            "match",
            ["get", "service"],
            ["siding", "spur", "yard"],
            3.6799999999999997,
            7.359999999999999,
          ],
          [
            "match",
            ["get", "service"],
            ["siding", "spur", "yard"],
            2.875,
            5.75,
          ],
        ],
      ],
      "line-dasharray": [0.2173913043478261, 0.4347826086956522],
    },
  },
  {
    type: "line",
    source: "georgia",
    "source-layer": "transportation",
    id: "rail_fill_tunnel",
    filter: [
      "all",
      ["match", ["get", "brunnel"], "tunnel", true, false],
      ["in", ["get", "class"], ["literal", ["rail", "transit"]]],
    ],
    minzoom: 10,
    layout: {
      "line-cap": "butt",
      "line-join": "bevel",
      visibility: "visible",
    },
    paint: {
      "line-color": [
        "match",
        ["get", "brunnel"],
        "tunnel",
        "hsl(0, 0%, 90%)",
        [
          "match",
          ["get", "subclass"],
          "subway",
          "hsl(0, 0%, 50%)",
          "light_rail",
          "hsl(0, 0%, 50%)",
          "tram",
          "hsl(0, 0%, 60%)",
          "monorail",
          "hsl(0, 0%, 50%)",
          "funicular",
          "hsl(0, 0%, 50%)",
          "narrow_gauge",
          "hsl(0, 0%, 60%)",
          "hsl(0, 0%, 60%)",
        ],
      ],
      "line-opacity": [
        "step",
        ["zoom"],
        [
          "match",
          ["get", "subclass"],
          ["rail", "preserved", "narrow_gauge"],
          1,
          0,
        ],
        14,
        1,
      ],
      "line-width": [
        "interpolate",
        ["exponential", 1.2],
        ["zoom"],
        8,
        [
          "match",
          ["get", "subclass"],
          ["rail", "preserved", "narrow_gauge", "subway"],
          [
            "match",
            ["get", "service"],
            ["siding", "spur", "yard"],
            0.125,
            0.25,
          ],
          "monorail",
          ["match", ["get", "service"], ["siding", "spur", "yard"], 0.1, 0.2],
          [
            "match",
            ["get", "service"],
            ["siding", "spur", "yard"],
            0.078125,
            0.15625,
          ],
        ],
        12,
        [
          "match",
          ["get", "subclass"],
          ["rail", "preserved", "narrow_gauge", "subway"],
          ["match", ["get", "service"], ["siding", "spur", "yard"], 0.5, 1],
          "monorail",
          ["match", ["get", "service"], ["siding", "spur", "yard"], 0.4, 0.8],
          [
            "match",
            ["get", "service"],
            ["siding", "spur", "yard"],
            0.3125,
            0.625,
          ],
        ],
        20,
        [
          "match",
          ["get", "subclass"],
          ["rail", "preserved", "narrow_gauge", "subway"],
          ["match", ["get", "service"], ["siding", "spur", "yard"], 2, 4],
          "monorail",
          ["match", ["get", "service"], ["siding", "spur", "yard"], 1.6, 3.2],
          ["match", ["get", "service"], ["siding", "spur", "yard"], 1.25, 2.5],
        ],
      ],
    },
  },
  {
    id: "road_service_case",
    type: "line",
    source: "georgia",
    "source-layer": "transportation",
    minzoom: 15,
    maxzoom: 24,
    filter: ["all", ["==", "class", "service"], ["!has", "brunnel"]],
    layout: {
      "line-cap": "round",
      "line-join": "round",
    },
    paint: {
      "line-width": [
        "interpolate",
        ["exponential", 1.2],
        ["zoom"],
        15,
        1,
        16,
        3,
        17,
        6,
        18,
        8,
      ],
      "line-opacity": 1,
      "line-color": "#ddd",
    },
  },
  {
    id: "road_minor_case",
    type: "line",
    source: "georgia",
    "source-layer": "transportation",
    minzoom: 15,
    maxzoom: 24,
    filter: ["all", ["==", "class", "minor"], ["!has", "brunnel"]],
    layout: {
      "line-cap": "round",
      "line-join": "round",
    },
    paint: {
      "line-width": [
        "interpolate",
        ["exponential", 1.2],
        ["zoom"],
        11,
        0.5,
        12,
        0.5,
        14,
        2,
        15,
        3,
        16,
        4.3,
        17,
        10,
        18,
        14,
      ],
      "line-opacity": 1,
      "line-color": [
        "interpolate",
        ["exponential", 1.2],
        ["zoom"],
        13,
        roadColor,
        15.7,
        roadColor,
        16,
        chroma(roadColor).darken(1).hex(),
      ],
    },
  },
  {
    id: "road_pri_case_ramp",
    type: "line",
    source: "georgia",
    "source-layer": "transportation",
    minzoom: 12,
    maxzoom: 24,
    filter: ["all", ["==", "class", "primary"], ["==", "ramp", 1]],
    layout: {
      "line-cap": "round",
      "line-join": "round",
    },
    paint: {
      "line-width": [
        "interpolate",
        ["exponential", 1.2],
        ["zoom"],
        12,
        2,
        13,
        3,
        14,
        4,
        15,
        5,
        16,
        8,
        17,
        10,
      ],
      "line-opacity": [
        "interpolate",
        ["exponential", 1.2],
        ["zoom"],
        5,
        0.5,
        7,
        1,
      ],
      "line-color": "#ddd",
    },
  },
  {
    id: "road_trunk_case_ramp",
    type: "line",
    source: "georgia",
    "source-layer": "transportation",
    minzoom: 12,
    maxzoom: 24,
    filter: ["all", ["==", "class", "trunk"], ["==", "ramp", 1]],
    layout: {
      "line-cap": "round",
      "line-join": "round",
    },
    paint: {
      "line-width": [
        "interpolate",
        ["exponential", 1.2],
        ["zoom"],
        12,
        2,
        13,
        3,
        14,
        4,
        15,
        5,
        16,
        8,
        17,
        10,
      ],
      "line-opacity": 1,
      "line-color": [
        "interpolate",
        ["exponential", 1.2],
        ["zoom"],
        12,
        roadColor,
        14,
        "#ddd",
      ],
    },
  },
  {
    id: "road_mot_case_ramp",
    type: "line",
    source: "georgia",
    "source-layer": "transportation",
    minzoom: 12,
    maxzoom: 24,
    filter: ["all", ["==", "class", "motorway"], ["==", "ramp", 1]],
    layout: {
      "line-cap": "round",
      "line-join": "round",
    },
    paint: {
      "line-width": [
        "interpolate",
        ["exponential", 1.2],
        ["zoom"],
        12,
        2,
        13,
        3,
        14,
        4,
        15,
        5,
        16,
        8,
        17,
        10,
      ],
      "line-opacity": 1,
      "line-color": [
        "interpolate",
        ["exponential", 1.2],
        ["zoom"],
        12,
        roadColor,
        14,
        "#ddd",
      ],
    },
  },
  {
    id: "road_sec_case_noramp",
    type: "line",
    source: "georgia",
    "source-layer": "transportation",
    minzoom: 11,
    maxzoom: 24,
    filter: [
      "all",
      ["in", "class", "secondary", "tertiary"],
      ["!has", "brunnel"],
    ],
    layout: {
      "line-cap": "round",
      "line-join": "round",
    },
    paint: {
      "line-width": [
        "interpolate",
        ["exponential", 1.2],
        ["zoom"],
        11,
        0.5,
        12,
        1.5,
        13,
        3,
        14,
        5,
        15,
        6,
        16,
        8,
        17,
        12,
        18,
        16,
      ],
      "line-opacity": 1,
      "line-color": [
        "interpolate",
        ["exponential", 1.2],
        ["zoom"],
        11,
        roadColor,
        12.99,
        roadColor,
        13,
        "#ddd",
      ],
    },
  },
  {
    id: "road_pri_case_noramp",
    type: "line",
    source: "georgia",
    "source-layer": "transportation",
    minzoom: 7,
    maxzoom: 24,
    filter: [
      "all",
      ["==", "class", "primary"],
      ["!=", "ramp", 1],
      ["!has", "brunnel"],
    ],
    layout: {
      "line-cap": "round",
      "line-join": "round",
    },
    paint: {
      "line-width": [
        "interpolate",
        ["exponential", 1.2],
        ["zoom"],
        6,
        0.5,
        7,
        0.8,
        8,
        1,
        11,
        3,
        13,
        4,
        14,
        6,
        15,
        8,
        16,
        10,
        17,
        14,
        18,
        18,
      ],
      "line-opacity": [
        "interpolate",
        ["exponential", 1.2],
        ["zoom"],
        5,
        0.5,
        7,
        1,
      ],
      "line-color": [
        "interpolate",
        ["exponential", 1.2],
        ["zoom"],
        7,
        roadColor,
        12,
        "#ddd",
      ],
    },
  },
  {
    id: "road_trunk_case_noramp",
    type: "line",
    source: "georgia",
    "source-layer": "transportation",
    minzoom: 5,
    maxzoom: 24,
    filter: [
      "all",
      ["==", "class", "trunk"],
      ["!=", "ramp", 1],
      ["!has", "brunnel"],
    ],
    layout: {
      "line-cap": "round",
      "line-join": "round",
    },
    paint: {
      "line-width": [
        "interpolate",
        ["exponential", 1.2],
        ["zoom"],
        6,
        0.5,
        7,
        0.8,
        8,
        1,
        11,
        3,
        13,
        4,
        14,
        6,
        15,
        8,
        16,
        10,
        17,
        14,
        18,
        18,
      ],
      "line-opacity": [
        "interpolate",
        ["exponential", 1.2],
        ["zoom"],
        5,
        0.5,
        7,
        1,
      ],
      "line-color": [
        "interpolate",
        ["exponential", 1.2],
        ["zoom"],
        5,
        roadColor,
        12,
        "#ddd",
      ],
    },
  },
  {
    type: "line",
    source: "georgia",
    "source-layer": "transportation",
    id: "rail_dashes_tunnel_all_in,get,subclass,literal,light_rail,tram_match,get,service,siding,spur,yard,false,true",
    filter: [
      "all",
      ["match", ["get", "brunnel"], "tunnel", true, false],
      ["in", ["get", "class"], ["literal", ["rail", "transit"]]],
      [
        "all",
        ["in", ["get", "subclass"], ["literal", ["light_rail", "tram"]]],
        ["match", ["get", "service"], ["siding", "spur", "yard"], false, true],
      ],
      ["!=", ["get", "service"], "crossover"],
    ],
    minzoom: 14,
    layout: {
      "line-cap": "butt",
      "line-join": "bevel",
      visibility: "visible",
    },
    paint: {
      "line-color": [
        "match",
        ["get", "brunnel"],
        "tunnel",
        "hsl(0, 0%, 90%)",
        [
          "match",
          ["get", "subclass"],
          "subway",
          "hsl(0, 0%, 50%)",
          "light_rail",
          "hsl(0, 0%, 50%)",
          "tram",
          "hsl(0, 0%, 60%)",
          "monorail",
          "hsl(0, 0%, 50%)",
          "funicular",
          "hsl(0, 0%, 50%)",
          "narrow_gauge",
          "hsl(0, 0%, 60%)",
          "hsl(0, 0%, 60%)",
        ],
      ],
      "line-opacity": [
        "step",
        ["zoom"],
        [
          "match",
          ["get", "subclass"],
          ["rail", "preserved", "narrow_gauge"],
          1,
          0,
        ],
        14,
        1,
      ],
      "line-width": [
        "interpolate",
        ["exponential", 1.2],
        ["zoom"],
        8,
        [
          "match",
          ["get", "subclass"],
          ["rail", "preserved", "narrow_gauge", "subway"],
          ["match", ["get", "service"], ["siding", "spur", "yard"], 0.25, 0.5],
          "monorail",
          ["match", ["get", "service"], ["siding", "spur", "yard"], 0.2, 0.4],
          [
            "match",
            ["get", "service"],
            ["siding", "spur", "yard"],
            0.15625,
            0.3125,
          ],
        ],
        12,
        [
          "match",
          ["get", "subclass"],
          ["rail", "preserved", "narrow_gauge", "subway"],
          ["match", ["get", "service"], ["siding", "spur", "yard"], 1, 2],
          "monorail",
          ["match", ["get", "service"], ["siding", "spur", "yard"], 0.8, 1.6],
          [
            "match",
            ["get", "service"],
            ["siding", "spur", "yard"],
            0.625,
            1.25,
          ],
        ],
        20,
        [
          "match",
          ["get", "subclass"],
          ["rail", "preserved", "narrow_gauge", "subway"],
          ["match", ["get", "service"], ["siding", "spur", "yard"], 4, 8],
          "monorail",
          ["match", ["get", "service"], ["siding", "spur", "yard"], 3.2, 6.4],
          ["match", ["get", "service"], ["siding", "spur", "yard"], 2.5, 5],
        ],
      ],
      "line-dasharray": [0.25, 1.5],
    },
  },
  {
    type: "line",
    source: "georgia",
    "source-layer": "transportation",
    id: "rail_dashes_tunnel_all_in,get,subclass,literal,light_rail,tram_match,get,service,siding,spur,yard,true,false",
    filter: [
      "all",
      ["match", ["get", "brunnel"], "tunnel", true, false],
      ["in", ["get", "class"], ["literal", ["rail", "transit"]]],
      [
        "all",
        ["in", ["get", "subclass"], ["literal", ["light_rail", "tram"]]],
        ["match", ["get", "service"], ["siding", "spur", "yard"], true, false],
      ],
      ["!=", ["get", "service"], "crossover"],
    ],
    minzoom: 14,
    layout: {
      "line-cap": "butt",
      "line-join": "bevel",
      visibility: "visible",
    },
    paint: {
      "line-color": [
        "match",
        ["get", "brunnel"],
        "tunnel",
        "hsl(0, 0%, 90%)",
        [
          "match",
          ["get", "subclass"],
          "subway",
          "hsl(0, 0%, 50%)",
          "light_rail",
          "hsl(0, 0%, 50%)",
          "tram",
          "hsl(0, 0%, 60%)",
          "monorail",
          "hsl(0, 0%, 50%)",
          "funicular",
          "hsl(0, 0%, 50%)",
          "narrow_gauge",
          "hsl(0, 0%, 60%)",
          "hsl(0, 0%, 60%)",
        ],
      ],
      "line-opacity": [
        "step",
        ["zoom"],
        [
          "match",
          ["get", "subclass"],
          ["rail", "preserved", "narrow_gauge"],
          1,
          0,
        ],
        14,
        1,
      ],
      "line-width": [
        "interpolate",
        ["exponential", 1.2],
        ["zoom"],
        8,
        [
          "match",
          ["get", "subclass"],
          ["rail", "preserved", "narrow_gauge", "subway"],
          [
            "match",
            ["get", "service"],
            ["siding", "spur", "yard"],
            0.375,
            0.75,
          ],
          "monorail",
          [
            "match",
            ["get", "service"],
            ["siding", "spur", "yard"],
            0.30000000000000004,
            0.6000000000000001,
          ],
          [
            "match",
            ["get", "service"],
            ["siding", "spur", "yard"],
            0.234375,
            0.46875,
          ],
        ],
        12,
        [
          "match",
          ["get", "subclass"],
          ["rail", "preserved", "narrow_gauge", "subway"],
          ["match", ["get", "service"], ["siding", "spur", "yard"], 1.5, 3],
          "monorail",
          [
            "match",
            ["get", "service"],
            ["siding", "spur", "yard"],
            1.2000000000000002,
            2.4000000000000004,
          ],
          [
            "match",
            ["get", "service"],
            ["siding", "spur", "yard"],
            0.9375,
            1.875,
          ],
        ],
        20,
        [
          "match",
          ["get", "subclass"],
          ["rail", "preserved", "narrow_gauge", "subway"],
          ["match", ["get", "service"], ["siding", "spur", "yard"], 6, 12],
          "monorail",
          [
            "match",
            ["get", "service"],
            ["siding", "spur", "yard"],
            4.800000000000001,
            9.600000000000001,
          ],
          ["match", ["get", "service"], ["siding", "spur", "yard"], 3.75, 7.5],
        ],
      ],
      "line-dasharray": [0.16666666666666666, 2],
    },
  },
  // {
  //   id: "road_mot_case_noramp",
  //   type: "line",
  //   source: "georgia",
  //   "source-layer": "transportation",
  //   minzoom: 5,
  //   maxzoom: 24,
  //   filter: [
  //     "all",
  //     ["==", "class", "motorway"],
  //     ["!=", "ramp", 1],
  //     ["!has", "brunnel"],
  //   ],
  //   layout: {
  //     "line-cap": "round",
  //     "line-join": "round",
  //   },
  //   paint: {
  //     "line-width": [
  //       "interpolate",
  //       ["exponential", 1.2],
  //       ["zoom"],
  //       0,
  //       0.5,
  //       7,
  //       0.7,
  //       8,
  //       0.8,
  //       11,
  //       3,
  //       12,
  //       4,
  //       13,
  //       5,
  //       14,
  //       7,
  //       15,
  //       9,
  //       16,
  //       11,
  //       17,
  //       13,
  //       18,
  //       22,
  //     ],
  //     "line-opacity": [
  //       "interpolate",
  //       ["exponential", 1.2],
  //       ["zoom"],
  //       6,
  //       0.5,
  //       7,
  //       1,
  //     ],
  //     "line-color": [
  //       "interpolate",
  //       ["exponential", 1.2],
  //       ["zoom"],
  //       5,
  //       roadColor,
  //       12,
  //       "#ddd",
  //     ],
  //   },
  // },
  // {
  //   id: "road_path",
  //   type: "line",
  //   source: "georgia",
  //   "source-layer": "transportation",
  //   minzoom: 15,
  //   maxzoom: 24,
  //   filter: ["all", ["in", "class", "path", "track"], ["!has", "brunnel"]],
  //   layout: {
  //     "line-cap": "round",
  //     "line-join": "round",
  //   },
  //   paint: {
  //     "line-width": [
  //       "interpolate",
  //       ["exponential", 1.2],
  //       ["zoom"],
  //       15,
  //       0.5,
  //       16,
  //       1,
  //       18,
  //       3,
  //     ],
  //     "line-opacity": 1,
  //     "line-color": "#d5d5d5",
  //     // "line-dasharray": [
  //     //   "interpolate",
  //     //   ["exponential", 1.2],
  //     //   ["zoom"],
  //     //   15,
  //     //   [2, 2],
  //     //   18,
  //     //   [3, 3],
  //     // ],
  //   },
  // },
  // {
  //   id: "road_service_fill",
  //   type: "line",
  //   source: "georgia",
  //   "source-layer": "transportation",
  //   minzoom: 15,
  //   maxzoom: 24,
  //   filter: ["all", ["==", "class", "service"], ["!has", "brunnel"]],
  //   layout: {
  //     "line-cap": "round",
  //     "line-join": "round",
  //   },
  //   paint: {
  //     "line-width": [
  //       "interpolate",
  //       ["exponential", 1.2],
  //       ["zoom"],
  //       15,
  //       2,
  //       16,
  //       2,
  //       17,
  //       4,
  //       18,
  //       6,
  //     ],
  //     "line-opacity": 1,
  //     "line-color": "#fdfdfd",
  //   },
  // },
  // {
  //   id: "road_minor_fill",
  //   type: "line",
  //   source: "georgia",
  //   "source-layer": "transportation",
  //   minzoom: 15,
  //   maxzoom: 24,
  //   filter: ["all", ["==", "class", "minor"], ["!has", "brunnel"]],
  //   layout: {
  //     "line-cap": "round",
  //     "line-join": "round",
  //   },
  //   paint: {
  //     "line-width": [
  //       "interpolate",
  //       ["exponential", 1.2],
  //       ["zoom"],
  //       15,
  //       3,
  //       16,
  //       4,
  //       17,
  //       8,
  //       18,
  //       12,
  //     ],
  //     "line-opacity": 1,
  //     "line-color": "#fdfdfd",
  //   },
  // },
  // {
  //   id: "road_pri_fill_ramp",
  //   type: "line",
  //   source: "georgia",
  //   "source-layer": "transportation",
  //   minzoom: 12,
  //   maxzoom: 24,
  //   filter: ["all", ["==", "class", "primary"], ["==", "ramp", 1]],
  //   layout: {
  //     "line-cap": "round",
  //     "line-join": "round",
  //   },
  //   paint: {
  //     "line-width": [
  //       "interpolate",
  //       ["exponential", 1.2],
  //       ["zoom"],
  //       12,
  //       1,
  //       13,
  //       1.5,
  //       14,
  //       2,
  //       15,
  //       3,
  //       16,
  //       6,
  //       17,
  //       8,
  //     ],
  //     "line-opacity": 1,
  //     "line-color": "#fff",
  //   },
  // },
  // {
  //   id: "road_trunk_fill_ramp",
  //   type: "line",
  //   source: "georgia",
  //   "source-layer": "transportation",
  //   minzoom: 12,
  //   maxzoom: 24,
  //   filter: ["all", ["==", "class", "trunk"], ["==", "ramp", 1]],
  //   layout: {
  //     "line-cap": "square",
  //     "line-join": "round",
  //   },
  //   paint: {
  //     "line-width": [
  //       "interpolate",
  //       ["exponential", 1.2],
  //       ["zoom"],
  //       12,
  //       1,
  //       13,
  //       1.5,
  //       14,
  //       2,
  //       15,
  //       3,
  //       16,
  //       6,
  //       17,
  //       8,
  //     ],
  //     "line-opacity": 1,
  //     "line-color": "#fff",
  //   },
  // },
  // {
  //   id: "road_mot_fill_ramp",
  //   type: "line",
  //   source: "georgia",
  //   "source-layer": "transportation",
  //   minzoom: 12,
  //   maxzoom: 24,
  //   filter: ["all", ["==", "class", "motorway"], ["==", "ramp", 1]],
  //   layout: {
  //     "line-cap": "round",
  //     "line-join": "round",
  //   },
  //   paint: {
  //     "line-width": [
  //       "interpolate",
  //       ["exponential", 1.2],
  //       ["zoom"],
  //       12,
  //       1,
  //       13,
  //       1.5,
  //       14,
  //       2,
  //       15,
  //       3,
  //       16,
  //       6,
  //       17,
  //       8,
  //     ],
  //     "line-opacity": 1,
  //     "line-color": "#fff",
  //   },
  // },
  // {
  //   id: "road_sec_fill_noramp",
  //   type: "line",
  //   source: "georgia",
  //   "source-layer": "transportation",
  //   minzoom: 15,
  //   maxzoom: 24,
  //   filter: [
  //     "all",
  //     ["in", "class", "secondary", "tertiary"],
  //     ["!has", "brunnel"],
  //   ],
  //   layout: {
  //     "line-cap": "round",
  //     "line-join": "round",
  //   },
  //   paint: {
  //     "line-width": [
  //       "interpolate",
  //       ["exponential", 1.2],
  //       ["zoom"],
  //       11,
  //       2,
  //       13,
  //       2,
  //       14,
  //       3,
  //       15,
  //       4,
  //       16,
  //       6,
  //       17,
  //       10,
  //       18,
  //       14,
  //     ],
  //     "line-opacity": 1,
  //     "line-color": "#fff",
  //   },
  // },
  // {
  //   id: "road_pri_fill_noramp",
  //   type: "line",
  //   source: "georgia",
  //   "source-layer": "transportation",
  //   minzoom: 10,
  //   maxzoom: 24,
  //   filter: [
  //     "all",
  //     ["==", "class", "primary"],
  //     ["!=", "ramp", 1],
  //     ["!has", "brunnel"],
  //   ],
  //   layout: {
  //     "line-cap": "round",
  //     "line-join": "round",
  //   },
  //   paint: {
  //     "line-width": [
  //       "interpolate",
  //       ["exponential", 1.2],
  //       ["zoom"],
  //       10,
  //       0.3,
  //       13,
  //       2,
  //       14,
  //       4,
  //       15,
  //       6,
  //       16,
  //       8,
  //       17,
  //       12,
  //       18,
  //       16,
  //     ],
  //     "line-opacity": 1,
  //     "line-color": "#fff",
  //   },
  // },
  // {
  //   id: "road_trunk_fill_noramp",
  //   type: "line",
  //   source: "georgia",
  //   "source-layer": "transportation",
  //   minzoom: 10,
  //   maxzoom: 24,
  //   filter: [
  //     "all",
  //     ["==", "class", "trunk"],
  //     ["!=", "ramp", 1],
  //     ["!has", "brunnel"],
  //   ],
  //   layout: {
  //     "line-cap": "round",
  //     "line-join": "round",
  //   },
  //   paint: {
  //     "line-width": [
  //       "interpolate",
  //       ["exponential", 1.2],
  //       ["zoom"],
  //       11,
  //       1,
  //       13,
  //       2,
  //       14,
  //       4,
  //       15,
  //       6,
  //       16,
  //       8,
  //       17,
  //       12,
  //       18,
  //       16,
  //     ],
  //     "line-opacity": 1,
  //     "line-color": "#fff",
  //   },
  // },
  // {
  //   id: "road_mot_fill_noramp",
  //   type: "line",
  //   source: "georgia",
  //   "source-layer": "transportation",
  //   minzoom: 10,
  //   maxzoom: 24,
  //   filter: [
  //     "all",
  //     ["==", "class", "motorway"],
  //     ["!=", "ramp", 1],
  //     ["!has", "brunnel"],
  //   ],
  //   layout: {
  //     "line-cap": "round",
  //     "line-join": "round",
  //   },
  //   paint: {
  //     "line-width": [
  //       "interpolate",
  //       ["exponential", 1.2],
  //       ["zoom"],
  //       10,
  //       1,
  //       12,
  //       2,
  //       13,
  //       3,
  //       14,
  //       5,
  //       15,
  //       7,
  //       16,
  //       9,
  //       17,
  //       11,
  //       18,
  //       20,
  //     ],
  //     "line-opacity": 1,
  //     "line-color": "#fff",
  //   },
  // },
];
